site_name: Webmaster Statistics Guide
site_description: Complete web analytics guide for beginners

theme:
  name: material
  language: en  # английский как основной
  palette:
    - scheme: default
      primary: olive
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes    # Позволяет папкам быть кликабельными
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.breadcrumbs
    - search.highlight
    - content.code.copy
    - navigation.path
    - toc.follow
    - content.action.edit    # Кнопка "Edit this page"
    - content.action.view    # Кнопка "View source"

edit_uri: edit/main/docs/

plugins:
  - awesome-pages
  - search:
      lang:
        - en
        - uk
        - ru
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true  # английский по умолчанию
          name: English
          build: true
          site_name: "Webmaster Statistics Guide"
        - locale: uk
          name: Українська
          build: true
          site_name: "Статистика для Вебмастеров"
        - locale: ru
          name: Русский
          build: true
          site_name: "Статистика для Вебмастеров"
  - blog:
      blog_dir: blog  # директория с постами блога
      post_dir: "{blog}/posts"  # где хранятся посты
      post_date_format: "yyyy-MM-dd"
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"  # файл с авторами
      categories: true
      categories_name: Категории
      categories_url_format: "category/{slug}"
      archive: true
      archive_name: Архив
      archive_date_format: "yyyy"
      archive_url_format: "archive/{date}"
      pagination: true
      pagination_per_page: 10
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
          remove_empty_space: true
          reduce_boolean_attributes: true
          remove_optional_attribute_quotes: false
      css_files:
          - stylesheets/extra.css
      js_files:
          - javascripts/extra.js

nav:
  - Home: index.md
  - Basics:
      - basics/index.md
      - What is Web Analytics: basics/web-analytics.md
      - Getting Started: basics/getting-started.md
  - Key Metrics:
      - analytics/index.md
      - Bounce Rate: analytics/bounce-rate.md
      - Time on Site: analytics/time-on-site.md
      - Conversions: analytics/conversions.md
  - Tools:
      - tools/index.md
      - Google Analytics: tools/google-analytics.md
      - Yandex.Metrica: tools/yandex-metrica.md
  - Glossary:
      - Overview: glossary/index.md
      - Fundamentals:
          - Overview: glossary/fundamentals/index.md
          - Pageviews: glossary/fundamentals/pageviews.md
          - Pageview & Screenview: glossary/fundamentals/pageview-screenview.md
          - Sessions: glossary/fundamentals/sessions.md
          - Unique Visitors: glossary/fundamentals/unique-visitors.md
          - Bounce Rate: glossary/fundamentals/bounce-rate.md
          - Exit Rate: glossary/fundamentals/exit-rate.md
          - Scroll Depth: glossary/fundamentals/scroll-depth.md
          - Viewport: glossary/fundamentals/viewport.md
          - Event Parameter: glossary/fundamentals/event-parameter.md
          - KPI: glossary/fundamentals/kpi.md
          - Metric vs Dimension: glossary/fundamentals/metric-vs-dimension.md
          - Real-time Analytics: glossary/fundamentals/real-time-analytics.md
          - User & Session: glossary/fundamentals/user-session.md

  - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:  # Убрал дублирование
      base_path: 'docs'
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/key-arg/docs-mkdocs
repo_name: key-arg/docs-mkdocs