site_name: Webmaster Statistics Guide
site_description: Complete web analytics guide for beginners

theme:
  name: material
  language: en  # английский как основной
  palette:
    - scheme: default
      primary: olive
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes    # Позволяет папкам быть кликабельными
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.breadcrumbs
    - search.highlight
    - content.code.copy
    - navigation.path
    - toc.follow
    - content.action.edit    # Кнопка "Edit this page"
    - content.action.view    # Кнопка "View source"

edit_uri: edit/main/docs/

plugins:
  - awesome-pages
  - search:
      lang:
        - en
        - uk
        - ru
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true  # английский по умолчанию
          name: English
          build: true
          site_name: "Webmaster Statistics Guide"
        - locale: uk
          name: Українська
          build: true
          site_name: "Статистика для Вебмастеров"
        - locale: ru
          name: Русский
          build: true
          site_name: "Статистика для Вебмастеров"

nav:
  - Home: index.md
  - Basics:
      - basics/index.md
      - What is Web Analytics: basics/web-analytics.md
      - Getting Started: basics/getting-started.md
  - Key Metrics:
      - analytics/index.md
      - Bounce Rate: analytics/bounce-rate.md
      - Time on Site: analytics/time-on-site.md
      - Conversions: analytics/conversions.md
  - Tools:
      - tools/index.md
      - Google Analytics: tools/google-analytics.md
      - Yandex.Metrica: tools/yandex-metrica.md
  - Glossary:
      - Overview: glossary/index.md
      - Fundamentals:
          - Overview: glossary/fundamentals/index.md
          - Pageviews: glossary/fundamentals/pageviews.md
          - Sessions: glossary/fundamentals/sessions.md
          - Unique Visitors: glossary/fundamentals/unique-visitors.md
          - Bounce Rate: glossary/fundamentals/bounce-rate.md
          - Analytics: glossary/fundamentals/analytics.md
          - Web Analytics: glossary/fundamentals/web-analytics.md
          - Cardinality: glossary/fundamentals/cardinality.md
          - Event Parameter: glossary/fundamentals/event-parameter.md
          - KPI: glossary/fundamentals/kpi.md
          - Metric vs Dimension: glossary/fundamentals/metric-vs-dimension.md
          - Pageview & Screenview: glossary/fundamentals/pageview-screenview.md
          - Property & Data Stream: glossary/fundamentals/property-data-stream.md
          - Real-time Analytics: glossary/fundamentals/real-time-analytics.md
          - Sampling & Thresholding: glossary/fundamentals/sampling-thresholding.md
          - User & Session: glossary/fundamentals/user-session.md
          - Hit (Legacy): glossary/fundamentals/hit-legacy.md
          - View (Legacy): glossary/fundamentals/view-legacy.md
  - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:  # Убрал дублирование
      base_path: 'docs'
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/key-arg/docs-mkdocs
repo_name: key-arg/docs-mkdocs